=== hasura/ndc-graphql/crates/ndc-graphql/tests/config-1/configuration/configuration.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "ServerConfigFile",
  "type": "object",
  "required": [
    "$schema",
    "execution",
    "introspection",
    "request",
    "response"
  ],
  "properties": {
    "$schema": {
      "type": "string"
    },
    "introspection": {
      "description": "Connection Configuration for introspection",
      "allOf": [
        {
          "$ref": "#/definitions/ConnectionConfigFile"
        }
      ]
    },
    "execution": {
      "description": "Connection configuration for query execution",
      "allOf": [
        {
          "$ref": "#/definitions/ConnectionConfigFile"
        }
      ]
    },
    "request": {
      "description": "Optional configuration for requests",
      "allOf": [
        {
          "$ref": "#/definitions/RequestConfigFile"
        }
      ]
    },
    "response": {
      "description": "Optional configuration for responses",
      "allOf": [
        {
          "$ref": "#/definitions/ResponseConfigFile"
        }
      ]
    }
  },
  "definitions": {
    "ConnectionConfigFile": {
      "type": "object",
      "required": [
        "endpoint"
      ],
      "properties": {
        "endpoint": {
          "$ref": "#/definitions/ConfigValue"
        },
        "headers": {
          "type": "object",
          "additionalProperties": {
            "$ref": "#/definitions/ConfigValue"
          }
        }
      }
    },
    "ConfigValue": {
      "oneOf": [
        {
          "type": "object",
          "required": [
            "value"
          ],
          "properties": {
            "value": {
              "type": "string"
            }
          },
          "additionalProperties": false
        },
        {
          "type": "object",
          "required": [
            "valueFromEnv"
          ],
          "properties": {
            "valueFromEnv": {
              "type": "string"
            }
          },
          "additionalProperties": false
        }
      ]
    },
    "RequestConfigFile": {
      "type": "object",
      "properties": {
        "headersArgument": {
          "description": "Name of the headers argument Must not conflict with any arguments of root fields in the target schema Defaults to \"_headers\", set to a different value if there is a conflict",
          "type": [
            "string",
            "null"
          ]
        },
        "headersTypeName": {
          "description": "Name of the headers argument type Must not conflict with other types in the target schema Defaults to \"_HeaderMap\", set to a different value if there is a conflict",
          "type": [
            "string",
            "null"
          ]
        },
        "forwardHeaders": {
          "description": "List of headers to from the request Defaults to [], AKA no headers/disabled Supports glob patterns eg. \"X-Hasura-*\" Enabling this requires additional configuration on the ddn side, see docs for more",
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string"
          }
        }
      }
    },
    "ResponseConfigFile": {
      "type": "object",
      "properties": {
        "headersField": {
          "description": "Name of the headers field in the response type Defaults to \"headers\"",
          "type": [
            "string",
            "null"
          ]
        },
        "responseField": {
          "description": "Name of the response field in the response type Defaults to \"response\"",
          "type": [
            "string",
            "null"
          ]
        },
        "typeNamePrefix": {
          "description": "Prefix for response type names Defaults to \"_\" Generated response type names must be unique once prefix and suffix are applied",
          "type": [
            "string",
            "null"
          ]
        },
        "typeNameSuffix": {
          "description": "Suffix for response type names Defaults to \"Response\" Generated response type names must be unique once prefix and suffix are applied",
          "type": [
            "string",
            "null"
          ]
        },
        "forwardHeaders": {
          "description": "List of headers to from the response Defaults to [], AKA no headers/disabled Supports glob patterns eg. \"X-Hasura-*\" Enabling this requires additional configuration on the ddn side, see docs for more",
          "type": [
            "array",
            "null"
          ],
          "items": {
            "type": "string"
          }
        }
      }
    }
  }
}

=== hasura/ndc-graphql/crates/ndc-graphql/tests/config-3/configuration/configuration.json
{
  "$schema": "configuration.schema.json",
  "introspection": {
    "endpoint": {
      "valueFromEnv": "GRAPHQL_ENDPOINT"
    },
    "headers": {
      "x-hasura-admin-secret": {
        "valueFromEnv": "GRAPHQL_ENDPOINT_SECRET"
      }
    }
  },
  "execution": {
    "endpoint": {
      "valueFromEnv": "GRAPHQL_ENDPOINT"
    },
    "headers": {}
  },
  "request": {
    "forwardHeaders": [
      "Authorization"
    ],
    "headersArgument": "_forwarded_headers"
  },
  "response": {
    "forwardHeaders": [
      "Set-Cookie"
    ]
  }
}

=== hasura/ndc-graphql/crates/ndc-graphql/tests/config-1/configuration/configuration.json
{
  "$schema": "configuration.schema.json",
  "introspection": {
    "endpoint": {
      "valueFromEnv": "GRAPHQL_ENDPOINT"
    },
    "headers": {
      "x-hasura-admin-secret": {
        "valueFromEnv": "GRAPHQL_ENDPOINT_SECRET"
      }
    }
  },
  "execution": {
    "endpoint": {
      "valueFromEnv": "GRAPHQL_ENDPOINT"
    },
    "headers": {
      "Authorization": {
        "value": "Bearer <token>"
      }
    }
  },
  "request": {},
  "response": {}
}
